"""add road_distance and route_geometry to orders

Revision ID: 5c4ce6d4334d
Revises: 
Create Date: 2026-07-14 18:55:46.359685
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5c4ce6d4334d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('road_distance_km', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('route_geometry', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'route_geometry')
    op.drop_column('orders', 'road_distance_km')
    # ### end Alembic commands ###
